# Generated by Django 2.1.2 on 2018-10-08 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_auto_20181008_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='quantity',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
