# Generated by Django 2.1.2 on 2018-10-08 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_auto_20181008_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
