# Generated by Django 2.1.2 on 2018-10-08 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_auto_20181008_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
