# Generated by Django 2.1.2 on 2018-10-08 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_auto_20181008_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
