# Generated by Django 2.1.2 on 2018-10-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0008_laptop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='slug',
            field=models.SlugField(),
        ),
    ]
